### ISSUE TITLE
Feature Requestchannel dependent scan-angle 

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/crtm#19]

**Comment by BenjaminTJohnson** [comment]
Per communication with Jianjun Jin at GMAO, there's a need for a channel-dependent scan angle specification in support of the GMI instrument.    Specifically, the GMI HF channels have a slight offset of scan angle relative to the LF channels.

Details are here:
https://gpm.nasa.gov/sites/default/files/2020-05/L1C_ATBD_v1.6_V04_0.pdf

"The L1C GMI Swath S2 (HF channels) scan does not quite match the Swath S1 (LF channels)
scan geometry, and the view angle is off by almost 4 degrees. To address this issue, the
L1CRgmi algorithm co-registers/collocates the L1C GMI HF field-of-view (FOV) position to
bring it as close to the corresponding LF FOV position as possible using the nearest-neighbor
matching approach."

**Comment by BenjaminTJohnson** [comment]
@gmao-jjin3  Please post the exact values for the zenith angle and scan angles for GMI LF and HF channels.  Note, these could be different before and after orbit boost (March 19, 2014?) -- so for long term reanalysis, this should be accounted for.

**Comment by gmao-jjin3** [comment]
@BenjaminTJohnson The incidence angle is about 52.8 degree for (LF) channel 1-9 and 49.2 degree for (HF) channel 10-13.  They are not true constants. The earliest data we have (1C) was on March 4, 2014.

GMI incidence angle (degree)  on 03/05/2014
LF, mean/std/max/min=      52.7640    0.0644983      52.9900      52.6600
HF, mean/std/max/min=      49.1974    0.0585518      49.3100      49.0100

GMI incidence angle (degree)  on  01/05/2021
LF, mean/std/max/min=      52.7858    0.0569682      52.9200      52.6800
HF, mean/std/max/min=      49.1179    0.0512851      49.2400      49.0200

**Comment by gmao-jjin3** [comment]
@BenjaminTJohnson  There wasn't much change in these incidence angles. Here are values after the boost.

GMI incidence angle (degree) on 03/21/2014
LF, mean/std/max/min=      52.8106    0.0625692      52.9700      52.6800
HF, mean/std/max/min=      49.1450    0.0569934      49.2900      49.0200

**Comment by BenjaminTJohnson** [comment]
The largest simulated TB difference that I see between these two angles is
at 10.65 V, which is as much as 3.7 K...  Yeah, I agree, this is a serious
problem for GMI simulation.
