### ISSUE TITLE
not able to download CRTM binary files

### ISSUE THREAD

**Issue by maroonaggie** [JCSDA/crtm#28]
$ sh Get_CRTM_Binary_Files.sh 
downloading fix_REL-2.4.0.tgz, please wait about 5 minutes (3.2 GB tar file)
tar (child): fix_REL-2.4.0.tgz: Cannot open: No such file or directory

Could you please check if the ftp link "ftp://ftp.ucar.edu/pub/cpaess/bjohns/fix_REL-2.4.0.tgz" works? Thanks!

**Comment by climbfuji** [comment]
Apologies for this! The URL has recently changed.

See [Update crtm and add crtm-fix from NOAA-EMC/JCSDA spack fork by climbfuji · Pull Request #34715 · spack/spack · GitHub 4](https://github.com/spack/spack/pull/34715/files) → var/spack/repos/builtin/packages/crtm-fix/package.py line 15 or 35.

**Comment by BenjaminTJohnson** [comment]
The FTP site has changed unexpectedly, you can download the new script here:



https://github.com/JCSDA/crtm/blob/release/REL-2.4.0/Get_CRTM_Binary_Files.sh
