### ISSUE TITLE
update  configuration/gfortran*.setup flags for Apple Silicon 

### ISSUE THREAD

**Issue by gmao-cda** [JCSDA/crtm#39]
## Affected Branch
`release/REL-2.4.0`

## Machine & env
1. Apple Silicon M1 Pro + Homebrew gcc version 13.1.0 (Homebrew GCC 13.1.0)
2. Apple Silicon M1 Pro + Homebrew gcc version 12.2.0 (Homebrew GCC 12.2.0)
3. Intel 6700 + ubuntu 22.04 LTS + gcc version 11.0

## Description
I'm building the REL-2.4.0 following the steps documented in `REDME.md` instead of using `ecbuild`. 
When running `./configure --prefix=${PWD}` in the **Build Step 1**, I got the following error
```
configure: error: Fortran compiler cannot create executables
```
The error tracing back shows that this was due to the compling flag `-mieee-fp` (`FCFLAGS` in `configuration/gfortran*.setup`) not supported by gfortran 12.2.0/13.1.0 on my Apple Silicon Macbook Pro.
After removing this flag, the CRTM can be built successfully.

The corrected one has been tested in the above three envs and passed building tests.

## Solution
I have updated this branch at https://github.com/gmao-cda/crtm/tree/fix/release/REL-2.4.0_armflag

1. One additional check is added to `configuration/gfortran.setup` and `configuration/gfortran-debug.setup` to see if the computer arch is arm64-based. If so, drop the`-mieee-fp` flag
2. Besides, remove the hard-coded approach to get `NC4_DIR` and `HDF_DIR` in `configuration/gfortran*.setup`.

**Comment by StegmannJCSDA** [comment]
Closed by PR #40.
