### ISSUE TITLE
installing in a user environment

### ISSUE THREAD

**Issue by stephentjemkes** [JCSDA/crtm#41]
The distributed installation guide and scripts assume a particular installation directory. This assumption may not be universal applicable.  the installation guide suggests the standard configuration syntax, 

./configure --prefix=/your/preferred/installation/path

it is a bit odd that some of the setup scripts (Set_CRTM_Environment.sh)
has a different syntax (a BINDIR has to be defined which is /your/preferred/installation/path/bin if i understood it correctly) and has to be run first. 
also all netcdf4/hdf5 libraries does not have to be available in the location which is hard coded in some of the scripts which has to be run first.
the setting of the BINDIR  and of the NC4_DIR, HDF_DIR   was not mentioned in the README.md file. This was causing some issues as the first attempt to compile as the first pass returned an error 

Once i had figured this out and modified in the fortran setup scripts
	export NC4_DIR=${HOME}/local/ #singularity container only
	export HDF_DIR=${HOME}/local/ #singularity container only

compilation went smooth, and make check went fine, make install worked also fine
I did not modify the BINDIR so not sure this is critical as my PATH environment has the ${HOME}/local/bin where all my code ends up (not to confuse the system directories).

Maybe you could update the README.md file to inform the new user of setting some of the environmental variables to local situation.

**Comment by BenjaminTJohnson** [comment]
@stephentjemkes much appreciated, you're right, it doesn't contain explicit instructions on this point.  
As a note, we're deprecating the autotools method of building CRTM in favor of `cmake`, since it greatly simplifies the finding of netCDF and HDF libraries, and is more in line with operational partner use requirements.
