### ISSUE TITLE
Fortran line lengths in v2.4.0_emc.3

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/crtm#45]
I am unable to compile v2.4.0_emc.3 with GCC (I tried with versions 8 and 11) on account of some lines in [RSS_Emissivity_Model.f90](https://github.com/JCSDA/crtm/blob/v2.4.0_emc.3/libsrc/RSS_Emissivity_Model.f90) being too long (i.e., past the default limit which I think is 132). I'm able to get around it by adding `-ffree-line-length-none` to CMAKE_Fortran_FLAGS in libsrc/CMakeLists.txt. On a related note, I would suggest allowing CMAKE_Fortran_FLAGS to accommodate user-provided values (from $FFLAGS env variable or by setting -DCMAKE_Fortran_FLAGS=... on the command line). I think doing something like `set(CMAKE_Fortran_FLAGS "-g -fbacktrace -fconvert=big-endian ${CMAKE_Fortran_FLAGS}")` would have that effect.

**Comment by BenjaminTJohnson** [comment]
Thanks for the comment.   Just as an FYI, there are modules for CRTM v2.4.0 available in HPC stack and Spack stacks.  
I agree with your suggestion in principle, it does add user flexibility.    However, it makes support much harder if additional flags are being passed in a script / command line and are not captured in the flags file.     For now, we'll stick with flags in the files -- you're going to have to re-compile anyway.  I'm happy to add the ffree-line-length-none flag to future CRTM versions.
