### ISSUE TITLE
Getting Started Guide points to Installing Singularity link which doesn't exist

### ISSUE THREAD

**Issue by 60south** [JCSDA/crtm#48]
URL not found:

https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/developer/jedi_environment/singularity.html

**Comment by 60south** [comment]
I believe the URL should point to here:
https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/using/jedi_environment/containers/singularity.html#installing-singularity

It might be good to also reference the Singularity 3.0 installation guide:
https://docs.sylabs.io/guides/3.0/user-guide/installation.html

**Comment by BenjaminTJohnson** [comment]
@60south Thanks.  We don't really support containers any longer for the CRTM -- this was just a convenience item that was developed for users who wanted a containerized environment, but it was very rarely used.     It may or may not still work.  I'm happy to help you setup CRTM in a stand-alone mode, if needed.
